# Auto-generated by asn1ate on 2017-08-06 15:44:48.568229
from pyasn1.type import univ, char, namedtype, namedval, tag, constraint, useful


class ReleaseVersionNumber(univ.Integer):
    pass


ReleaseVersionNumber.tagSet = univ.Integer.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 37))


class NumberString(univ.OctetString):
    pass


class FileAvailableTimeStamp(NumberString):
    pass


FileAvailableTimeStamp.tagSet = NumberString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 31))


class BCDString(univ.OctetString):
    pass


class Imei(BCDString):
    pass


Imei.tagSet = BCDString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 33))


class CallEventDuration(univ.Integer):
    pass


CallEventDuration.tagSet = univ.Integer.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 19))


class CallEventStartTimeStamp(NumberString):
    pass


CallEventStartTimeStamp.tagSet = NumberString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 21))


class CauseForTermination(univ.Integer):
    pass


CauseForTermination.tagSet = univ.Integer.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 24))


class Imsi(BCDString):
    pass


Imsi.tagSet = BCDString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 34))


class CallReference(univ.Integer):
    pass


CallReference.tagSet = univ.Integer.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 23))


class ChargeAmount(univ.Integer):
    pass


ChargeAmount.tagSet = univ.Integer.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 25))


class AsciiString(univ.OctetString):
    pass


class ServingNetwork(AsciiString):
    pass


ServingNetwork.tagSet = AsciiString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 15))


class UtcTimeOffset(AsciiString):
    pass


UtcTimeOffset.tagSet = AsciiString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 45))


class CallingNumber(NumberString):
    pass


CallingNumber.tagSet = NumberString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 22))


class Msisdn(BCDString):
    pass


Msisdn.tagSet = BCDString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 49))


class CellId(univ.Integer):
    pass


CellId.tagSet = univ.Integer.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 47))


class LocationArea(univ.Integer):
    pass


LocationArea.tagSet = univ.Integer.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 48))


class RecEntityId(AsciiString):
    pass


RecEntityId.tagSet = AsciiString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 35))


class HexString(univ.OctetString):
    pass


class TeleServiceCode(HexString):
    pass


TeleServiceCode.tagSet = HexString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 43))


class BearerServiceCode(HexString):
    pass


BearerServiceCode.tagSet = HexString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 18))


class ServiceCode(univ.Choice):
    pass


ServiceCode.tagSet = univ.Choice.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatConstructed, 46))
ServiceCode.componentType = namedtype.NamedTypes(
    namedtype.NamedType('teleServiceCode', TeleServiceCode()),
    namedtype.NamedType('bearerServiceCode', BearerServiceCode())
)


class Mtc(univ.Sequence):
    pass


Mtc.tagSet = univ.Sequence.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatConstructed, 4))
Mtc.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('imsi', Imsi()),
    namedtype.OptionalNamedType('imei', Imei()),
    namedtype.OptionalNamedType('callEventStartTimeStamp', CallEventStartTimeStamp()),
    namedtype.OptionalNamedType('utcTimeOffset', UtcTimeOffset()),
    namedtype.OptionalNamedType('callEventDuration', CallEventDuration()),
    namedtype.OptionalNamedType('causeForTermination', CauseForTermination()),
    namedtype.OptionalNamedType('serviceCode', ServiceCode()),
    namedtype.OptionalNamedType('callingNumber', CallingNumber()),
    namedtype.OptionalNamedType('recEntityId', RecEntityId()),
    namedtype.OptionalNamedType('callReference', CallReference()),
    namedtype.OptionalNamedType('chargeAmount', ChargeAmount()),
    namedtype.OptionalNamedType('servingNetwork', ServingNetwork()),
    namedtype.OptionalNamedType('msisdn', Msisdn()),
    namedtype.OptionalNamedType('locationArea', LocationArea()),
    namedtype.OptionalNamedType('cellId', CellId())
)


class AccessPointNameNI(AsciiString):
    pass


AccessPointNameNI.tagSet = AsciiString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 16))


class DataVolumeIncoming(univ.Integer):
    pass


DataVolumeIncoming.tagSet = univ.Integer.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 28))


class SgsnAddress(AsciiString):
    pass


SgsnAddress.tagSet = AsciiString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 40))


class GgsnAddress(AsciiString):
    pass


GgsnAddress.tagSet = AsciiString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 32))


class ChargingId(univ.Integer):
    pass


ChargingId.tagSet = univ.Integer.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 26))


class DataVolumeOutgoing(univ.Integer):
    pass


DataVolumeOutgoing.tagSet = univ.Integer.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 29))


class AccessPointNameOI(AsciiString):
    pass


AccessPointNameOI.tagSet = AsciiString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 17))


class Gprs(univ.Sequence):
    pass


Gprs.tagSet = univ.Sequence.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatConstructed, 5))
Gprs.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('imsi', Imsi()),
    namedtype.OptionalNamedType('imei', Imei()),
    namedtype.OptionalNamedType('callEventStartTimeStamp', CallEventStartTimeStamp()),
    namedtype.OptionalNamedType('utcTimeOffset', UtcTimeOffset()),
    namedtype.OptionalNamedType('callEventDuration', CallEventDuration()),
    namedtype.OptionalNamedType('causeForTermination', CauseForTermination()),
    namedtype.OptionalNamedType('accessPointNameNI', AccessPointNameNI()),
    namedtype.OptionalNamedType('accessPointNameOI', AccessPointNameOI()),
    namedtype.OptionalNamedType('dataVolumeIncoming', DataVolumeIncoming()),
    namedtype.OptionalNamedType('dataVolumeOutgoing', DataVolumeOutgoing()),
    namedtype.OptionalNamedType('sgsnAddress', SgsnAddress()),
    namedtype.OptionalNamedType('ggsnAddress', GgsnAddress()),
    namedtype.OptionalNamedType('chargingId', ChargingId()),
    namedtype.OptionalNamedType('chargeAmount', ChargeAmount()),
    namedtype.OptionalNamedType('servingNetwork', ServingNetwork()),
    namedtype.OptionalNamedType('msisdn', Msisdn()),
    namedtype.OptionalNamedType('locationArea', LocationArea()),
    namedtype.OptionalNamedType('cellId', CellId())
)


class ConnectedNumber(NumberString):
    pass


ConnectedNumber.tagSet = NumberString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 27))


class SupplementaryServiceCode(HexString):
    pass


SupplementaryServiceCode.tagSet = HexString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 42))


class ThirdPartyNumber(NumberString):
    pass


ThirdPartyNumber.tagSet = NumberString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 44))


class DialledDigits(AsciiString):
    pass


DialledDigits.tagSet = AsciiString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 30))


class Moc(univ.Sequence):
    pass


Moc.tagSet = univ.Sequence.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatConstructed, 3))
Moc.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('imsi', Imsi()),
    namedtype.OptionalNamedType('imei', Imei()),
    namedtype.OptionalNamedType('callEventStartTimeStamp', CallEventStartTimeStamp()),
    namedtype.OptionalNamedType('utcTimeOffset', UtcTimeOffset()),
    namedtype.OptionalNamedType('callEventDuration', CallEventDuration()),
    namedtype.OptionalNamedType('causeForTermination', CauseForTermination()),
    namedtype.OptionalNamedType('serviceCode', ServiceCode()),
    namedtype.OptionalNamedType('supplementaryServiceCode', SupplementaryServiceCode()),
    namedtype.OptionalNamedType('dialledDigits', DialledDigits()),
    namedtype.OptionalNamedType('connectedNumber', ConnectedNumber()),
    namedtype.OptionalNamedType('thirdPartyNumber', ThirdPartyNumber()),
    namedtype.OptionalNamedType('recEntityId', RecEntityId()),
    namedtype.OptionalNamedType('callReference', CallReference()),
    namedtype.OptionalNamedType('chargeAmount', ChargeAmount()),
    namedtype.OptionalNamedType('servingNetwork', ServingNetwork()),
    namedtype.OptionalNamedType('msisdn', Msisdn()),
    namedtype.OptionalNamedType('locationArea', LocationArea()),
    namedtype.OptionalNamedType('cellId', CellId())
)


class CallEvent(univ.Choice):
    pass


CallEvent.componentType = namedtype.NamedTypes(
    namedtype.NamedType('moc', Moc()),
    namedtype.NamedType('mtc', Mtc()),
    namedtype.NamedType('gprs', Gprs())
)


class CallEventList(univ.SequenceOf):
    pass


CallEventList.tagSet = univ.SequenceOf.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 2))
CallEventList.componentType = CallEvent()


class Recipient(AsciiString):
    pass


Recipient.tagSet = AsciiString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 36))


class SpecificationVersionNumber(univ.Integer):
    pass


SpecificationVersionNumber.tagSet = univ.Integer.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 41))


class CallEventsCount(univ.Integer):
    pass


CallEventsCount.tagSet = univ.Integer.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 20))


class SequenceNumber(NumberString):
    pass


SequenceNumber.tagSet = NumberString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 39))


class Sender(AsciiString):
    pass


Sender.tagSet = AsciiString.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatSimple, 38))


class Nrtrde(univ.Sequence):
    pass


Nrtrde.tagSet = univ.Sequence.tagSet.tagImplicitly(tag.Tag(tag.tagClassApplication, tag.tagFormatConstructed, 1))
Nrtrde.componentType = namedtype.NamedTypes(
    namedtype.OptionalNamedType('specificationVersionNumber', SpecificationVersionNumber()),
    namedtype.OptionalNamedType('releaseVersionNumber', ReleaseVersionNumber()),
    namedtype.OptionalNamedType('sender', Sender()),
    namedtype.OptionalNamedType('recipient', Recipient()),
    namedtype.OptionalNamedType('sequenceNumber', SequenceNumber()),
    namedtype.OptionalNamedType('fileAvailableTimeStamp', FileAvailableTimeStamp()),
    namedtype.OptionalNamedType('utcTimeOffset', UtcTimeOffset()),
    namedtype.OptionalNamedType('callEvents', CallEventList()),
    namedtype.OptionalNamedType('callEventsCount', CallEventsCount())
)


